import { LegalPage, LegalSection } from "@/components/legal-page";

const sections: LegalSection[] = [
  {
    heading: "Acceptance of Terms",
    body:
      "By creating an account or using the NATTA mobile application (the \"App\"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the App.",
  },
  {
    heading: "Eligibility",
    body:
      "You must be at least 16 years old (or the minimum legal age in your country) to create an account. By signing up, you represent that the information you provide is accurate and that you have the legal capacity to enter into this agreement.",
  },
  {
    heading: "Your Account",
    body:
      "You are responsible for keeping your login credentials secure and for all activity that occurs under your account. Notify us immediately at contato@natta.pro if you suspect unauthorized access.",
  },
  {
    heading: "Acceptable Use",
    body:
      "You agree not to misuse the App, including (but not limited to) attempting to access the App through unauthorized means, uploading malicious content, harassing other users, or violating any applicable law.",
  },
  {
    heading: "User Content",
    body:
      "You retain ownership of the content you submit to the App (such as resumes, interview answers, and notes). By submitting content, you grant NATTA a limited license to store, process, and display it solely to provide the App's features to you.",
  },
  {
    heading: "Intellectual Property",
    body:
      "The App, including its design, code, branding, and underlying technology, is the property of NATTA and its licensors and is protected by intellectual property laws.",
  },
  {
    heading: "Subscriptions and Payments",
    body:
      "Some features may require a paid subscription. Pricing, billing cycles, and cancellation terms will be disclosed at the point of purchase. Refunds are handled in accordance with the platform store policies (Apple App Store or Google Play).",
  },
  {
    heading: "Termination",
    body:
      "We may suspend or terminate your access to the App at any time if you violate these Terms or engage in activity that harms NATTA, its users, or third parties. You may delete your account at any time from the account settings.",
  },
  {
    heading: "Disclaimers",
    body:
      "The App is provided on an \"as is\" and \"as available\" basis. We do not guarantee that the App will be uninterrupted, error-free, or that any content generated by AI features is accurate or appropriate for a specific purpose.",
  },
  {
    heading: "Limitation of Liability",
    body:
      "To the maximum extent permitted by law, NATTA will not be liable for any indirect, incidental, consequential, or punitive damages arising from your use of the App.",
  },
  {
    heading: "Changes to These Terms",
    body:
      "We may update these Terms from time to time. We will notify you of material changes through the App or by email. Continued use after changes take effect constitutes acceptance of the updated Terms.",
  },
  {
    heading: "Governing Law",
    body:
      "These Terms are governed by the laws of Brazil. Any disputes will be resolved in the courts of São Paulo, Brazil, unless a mandatory consumer law in your country provides otherwise.",
  },
];

export default function TermsScreen() {
  return (
    <LegalPage
      title="Terms of Service"
      lastUpdated="May 14, 2026"
      intro="Welcome to NATTA. These Terms of Service govern your use of the NATTA mobile application and the services we provide. Please read them carefully."
      sections={sections}
    />
  );
}
